### ISSUE TITLE
Api to connect to gbwhatsapp. 

### ISSUE THREAD

**Issue by olamilekan000** [AndroidAppz/GBWhatsapp#4]
There's no api to connect to gbwhatsapp from another app.

**Comment by Bluscream** [comment]
What do you mean?

**Comment by olamilekan000** [comment]
Like I have an app and I want to connect it to gbwhatsapp so I can send stuffs from there instead of using gbwhatsapp directly.

**Comment by olamilekan000** [comment]
Like I have an app and I want to connect it to gbwhatsapp so I can send stuffs from there instead of using gbwhatsapp directly.

**Comment by Bluscream** [comment]
That's not in my control. Try to contact GBMods directly https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.gbmods.co%2F&edit-text=&act=url
